config/routes.rb
Rails.application.routes.draw do
  resources :documentary_films
  resources :series
  resources :movies
  root "series#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  before_action :set_documentary_film, only: %i[ show edit update destroy ]

  # GET /documentary_films or /documentary_films.json
  def index
    @documentary_films = DocumentaryFilm.all
  end

  # GET /documentary_films/1 or /documentary_films/1.json
  def show
  end

  # GET /documentary_films/new
  def new
    @documentary_film = DocumentaryFilm.new
  end

  # GET /documentary_films/1/edit
  def edit
  end

  # POST /documentary_films or /documentary_films.json
  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)

    respond_to do |format|
      if @documentary_film.save
        format.html { redirect_to documentary_film_url(@documentary_film), notice: "Documentary film was successfully created." }
        format.json { render :show, status: :created, location: @documentary_film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @documentary_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentary_films/1 or /documentary_films/1.json
  def update
    respond_to do |format|
      if @documentary_film.update(documentary_film_params)
        format.html { redirect_to documentary_film_url(@documentary_film), notice: "Documentary film was successfully updated." }
        format.json { render :show, status: :ok, location: @documentary_film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @documentary_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentary_films/1 or /documentary_films/1.json
  def destroy
    @documentary_film.destroy

    respond_to do |format|
      format.html { redirect_to documentary_films_url, notice: "Documentary film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentary_film
      @documentary_film = DocumentaryFilm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def documentary_film_params
      params.require(:documentary_film).permit(:name, :synopsis, :director)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :synopsis, :director)
    end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Serie.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Serie.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Serie.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_url(@series), notice: "Serie was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to series_url(@series), notice: "Serie was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_url, notice: "Serie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Serie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:name, :synopsis, :director)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/_documentary_film.html.erb
<div id="<%= dom_id documentary_film %>">
  <p>
    <strong>Name:</strong>
    <%= documentary_film.name %>
  </p>

  <p>
    <strong>Synopsis:</strong>
    <%= documentary_film.synopsis %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= documentary_film.director %>
  </p>

</div>

app/views/documentary_films/_form.html.erb
<%= form_with(model: documentary_film) do |form| %>
  <% if documentary_film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(documentary_film.errors.count, "error") %> prohibited this documentary_film from being saved:</h2>

      <ul>
        <% documentary_film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, style: "display: block" %>
    <%= form.text_field :synopsis %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documentary_films/edit.html.erb
<h1>Editing documentary film</h1>

<%= render "form", documentary_film: @documentary_film %>

<br>

<div>
  <%= link_to "Show this documentary film", @documentary_film %> |
  <%= link_to "Back to documentary films", documentary_films_path %>
</div>

app/views/documentary_films/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documentary films</h1>

<div id="documentary_films">
  <% @documentary_films.each do |documentary_film| %>
    <%= render documentary_film %>
    <p>
      <%= link_to "Show this documentary film", documentary_film %>
    </p>
  <% end %>
</div>

<%= link_to "New documentary film", new_documentary_film_path %>

app/views/documentary_films/new.html.erb
<h1>New documentary film</h1>

<%= render "form", documentary_film: @documentary_film %>

<br>

<div>
  <%= link_to "Back to documentary films", documentary_films_path %>
</div>

app/views/documentary_films/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @documentary_film %>

<div>
  <%= link_to "Edit this documentary film", edit_documentary_film_path(@documentary_film) %> |
  <%= link_to "Back to documentary films", documentary_films_path %>

  <%= button_to "Destroy this documentary film", @documentary_film, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav>
      <ul>
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Documentary films", documentary_films_path %>
        </li>
        <li>
          <%= link_to "Series", series_index_path %>
        </li>
        <li>
          <%= link_to "Movies", movies_path %>
        </li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, style: "display: block" %>
    <%= form.text_field :synopsis %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Name:</strong>
    <%= movie.name %>
  </p>

  <p>
    <strong>Synopsis:</strong>
    <%= movie.synopsis %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= movie.director %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, style: "display: block" %>
    <%= form.text_field :synopsis %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/series/_serie.html.erb
<div id="<%= dom_id serie %>">
  <p>
    <strong>Name:</strong>
    <%= serie.name %>
  </p>

  <p>
    <strong>Synopsis:</strong>
    <%= serie.synopsis %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= serie.director %>
  </p>

</div>

app/views/series/edit.html.erb
<h1>Editing serie</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Show this serie", @series %> |
  <%= link_to "Back to series", series_path %>
</div>

app/views/series/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Series</h1>

<div id="series">
  <% @series.each do |series| %>
    <%= render series %>
    <p>
      <%= link_to "Show this serie", series %>
    </p>
  <% end %>
</div>

<%= link_to "New serie", new_series_path %>

app/views/series/new.html.erb
<h1>New serie</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Back to series", series_path %>
</div>

app/views/series/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @series %>

<div>
  <%= link_to "Edit this serie", edit_series_path(@series) %> |
  <%= link_to "Back to series", series_path %>

  <%= button_to "Destroy this serie", @series, method: :delete %>
</div>